#!/usr/bin/env python

import re
import time

import requests

API = "https://dpaste.com/api/v2/"


# create a new paste and return its link
def create(content: str) -> str:
    headers = {"User-Agent": "matterbot"}
    data = {"content": content, "expiry_days": 30}
    with requests.post(API, data, headers=headers) as resp:
        if resp.status_code == 201:
            return resp.text.strip()
    return "(error: code block not relayed)"


def clean(text: str) -> str:
    regex = r"`{3}[^`]*`{3}"
    urls, message = [], ""

    # iterate over code blocks and clean them
    codeblocks = re.findall(regex, text)
    for i, block in enumerate(codeblocks):
        if len(block.split("\n")) > 1:
            # ```py\nprint()\n``` -> print()
            block = re.sub(r"^.*\n|\n`{3}$", "", block)
        else:
            # ``` print() ``` -> print()
            block = re.sub(r"^`{3}\s*|\s*`{3}$", "", block)
        # the recommended request rate is no more than one per second
        # see https://dpaste.com/api/
        urls.append(create(block))
        if len(codeblocks) > (i + 1):
            time.sleep(1)

    # replace code blocks
    text = re.sub(regex, "{CODEBLOCK}", text)
    for line in text.split("\n"):
        if line == "{CODEBLOCK}":
            message += f"{urls.pop(0)}\n"
            continue
        message += f"{line}\n"
    return message.strip()


if __name__ == "__main__":
    with open("message.txt") as file:
        message = file.read()
        print(clean(message))
